### ISSUE TITLE
extra `--partition` argument needed in `salloc` example?

### ISSUE THREAD

**Issue by wood-chris** [EPCCed/archer2-intro-develop#21]
I might be doing something wrong, but is the `partition`  flag needed in the `salloc` command

> salloc --nodes=2 --ntasks-per-node=128 --cpus-per-task=1 --time=0:10:0 --account=t01

this results in:

> salloc: error: Job rejected: Please specify a partition name.

The ARCHER2 docs example is

> auser@uan01:> salloc --nodes=8 --tasks-per-node=128 --cpus-per-task=1 \
              --time=00:20:00 --partition=standard --qos=short \
              --reservation=shortqos --account=[budget code]

**Comment by welucas2** [comment]
There's also some outdated information about whether the partition and QoS need to be specified further up in the same section. I'm fixing all these now for next week's course.

**Comment by welucas2** [comment]
This comment is correct, and several other batch commands were also incorrect. Fixed in commit 0781d596. Thanks!
